dataset_name: anet
train_split: [ 'training' ]
val_split: [ 'validation' ]
dataset: {
  json_file: ./data/anet_1.3/annotations/anet1.3_tsp_filtered.json,
  feat_folder: ./data/anet_1.3/tsp_features,
  file_prefix: v_,
  file_ext: .npy,
  num_classes: 1,
  input_dim: 512,
  feat_stride: 16,
  num_frames: 16,
  default_fps: 15,
  trunc_thresh: 0.5,
  crop_ratio: [ 0.9, 1.0 ],
  max_seq_len: 768,
}
model: {
  fpn_type: identity,
  max_buffer_len_factor: 1.0,
  backbone_arch: [ 2, 2, 5 ],
  n_sgp_win_size: 15,
  regression_range: [ [ 0, 4 ], [ 4, 8 ], [ 8, 16 ], [ 16, 32 ], [ 32, 64 ], [ 64, 10000 ] ],
  embd_dim: 256,
  sgp_mlp_dim: 2048,
  fpn_dim: 256,
  head_dim: 512,
  use_abs_pe: True,
  num_bins: 12,
  iou_weight_power: 1,
  input_noise: 0.5,
  k: 1.3,
  init_conv_vars: 0.2,
}
opt: {
  learning_rate: 0.001,
  eta_min: 0.00005,
  warmup_epochs: 10,
  epochs: 5,
  weight_decay: 0.04,
}
loader: {
  batch_size: 16,
}
train_cfg: {
  init_loss_norm: 400,
  clip_grad_l2norm: 0.4,
  cls_prior_prob: 0.01,
  center_sample: radius,
  center_sample_radius: 1.5,
  label_smoothing: 0.1,
}

# similar to THUMOS
test_cfg: {
  voting_thresh: 0.95,
  pre_nms_topk: 2000,
  # max of 200 predictions per video
  max_seg_num: 200,
  min_score: 0.001,
  # score fusion
  multiclass_nms: False,
  nms_sigma: 0.70,
  ext_score_file: ./data/anet_1.3/annotations/cuhk_val_simp_share.json,
  duration_thresh: 0.1,
}
output_folder: ./ckpt/
